baseURL = 'https://marcelorodrigo.com/'
languageCode = 'en-us'
title = 'Marcelo Rodrigo'
theme = "hugo-theme-monochrome"
description = "Apaixonado por viagens e bicicletas, brasileiro morando na Holanda"
enableRobotsTXT = true
defaultContentLanguage = "en"
enableEmoji = true

[params]
author = "Marcelo Rodrigo"