name: Check broken links
on: pull_request
jobs:
  htmltest:
    name: Check HTML
    runs-on: ubuntu-latest
    steps:
        - name: Check out
          uses: actions/checkout@v7
          with:
            submodules: recursive
            show-progress: false
        - name: Setup Node.js
          uses: actions/setup-node@v7
          with:
            node-version: '24'
            cache: 'npm'
        - name: Install npm dependencies (frozen)
          run: npm ci
        - name: Read .env
          uses: aarcangeli/load-dotenv@v1
          with:
            expand: true
        - name: Set up Hugo
          uses: peaceiris/actions-hugo@v3
          with:
            hugo-version: ${{env.HUGO_VERSION}}
            extended: true
        - name: Run Hugo
          run: hugo --logLevel debug
        - name: Test HTML
          continue-on-error: true
          uses: wjdp/htmltest-action@master
          with:
            path: public
        - name: Archive htmltest results
          uses: actions/upload-artifact@v7
          with:
            name: htmltest-report
            path: tmp/.htmltest/htmltest.log
            retention-days: 7
          
          
      
          
        
      
