name: Check broken links
on: pull_request
jobs:
  htmltest:
    runs-on: ubuntu-latest
    steps:
        - name: Check out
          uses: actions/checkout@v4
          with:
            submodules: recursive
        - name: Set up Hugo
          uses: peaceiris/actions-hugo@v2
          with:
            hugo-version: "latest"
        - name: Run Hugo
          run: hugo -s site
        - name: Test HTML
          continue-on-error: true
          uses: wjdp/htmltest-action@master
          with:
            config: .htmltest.yml
        - name: Archive htmltest results
          uses: actions/upload-artifact@v4
          with:
            name: htmltest-report
            path: tmp/.htmltest/htmltest.log
            retention-days: 7
          
          
      
          
        
      
